language: php

dist: trusty
php:
  - "7.2"
  - "7.1"
  - "7.0"
  - "5.6"
  - "5.5"
  - "5.4"

matrix:
  include:
    - php: "5.3"
      dist: precise

before_script:
  - composer install -n --dev --prefer-source

script:
  - vendor/bin/phpcs --standard=PSR2 src
  - vendor/bin/phpunit --verbose --coverage-clover coverage.clover

after_success:
  - wget https://scrutinizer-ci.com/ocular.phar
  - php ocular.phar code-coverage:upload --format=php-clover coverage.clover
